# numpy
- 수치 연산에 최적화된 Python 라이브러리
- 다차원 배열 연산 처리 가능함
- 선형대수 등 다양한 수학 연산 지원함
- Python list 대비 시간/공간 효율이 좋음


## 환경설정
- NumPy 설치 및 버전 확인용 섹션


In [1]:
# NumPy 설치
!pip install numpy

In [2]:
# NumPy import 및 설치 확인
import numpy as np

np.__version__

'2.4.6'

## ndarray
- N-dimensional array의 약자
- 다차원 데이터를 저장하고 연산하는 NumPy 배열 타입
- 같은 배열 안의 원소는 하나의 `dtype`을 가짐


In [9]:
# ndarray 생성
a = np.array([1, 2, 3]) # 1차원 ndarray 생성
print(type(a))
print(a)

b = np.array([4, 5, 6])

# ndarray 연산
c = a + b
print(f'a : {a}')
print(f'b : {b}')
print(f'c : {c}') # a와 b의 같은 인덱스 끼리 '+' 연산 후
                  # 같은 차원 / 같은 개수 결과 반환

# ndarray의 차원 크기, 요소 개수 확인
print(f'a.shape : {a.shape}') # (3,) == 1차원에 요소가 3개
print(f'a.size : {a.size}') # 3 == ndarray의 전체 요소 개수

<class 'numpy.ndarray'>
[1 2 3]
a : [1 2 3]
b : [4 5 6]
c : [5 7 9]
a.shape : (3,)
a.size : 3


### 실습
- 과일 판매량 데이터 사용함
- NumPy 배열로 분기별 판매량 계산함
- 구할 값: 과일별 총 판매량, 과일별 평균 판매량

- **데이터**
  - 1분기 판매량: `[200, 340, 150, 400]`
  - 2분기 판매량: `[220, 300, 180, 420]`
  - 과일 순서: 사과, 배, 오렌지, 바나나


In [18]:
fruits = ['사과', '배', '오렌지', '바나나']
sales_q1 = np.array([200, 340, 150, 400]) # 1분기(quarter 1)
sales_q2 = np.array([220, 300, 180, 420]) # 2분기(quarter 2)

# 1분기, 2분기 과일별 총 판매량
total_sales = sales_q1 + sales_q2
print(f'과일명: {fruits}')
print(f'과일별 총 판매량: {total_sales}')

# 과일별 평균 판매량
average_sales = total_sales / 2 # 각 요소별로 '/2' 연산이 적용
print(f'과일별 평균 판매량: {average_sales}')

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

### ndarray 속성
- `shape`: 배열의 모양
- `ndim`: 배열의 차원 수
- `size`: 전체 원소 개수
- `dtype`: 배열 원소의 데이터 타입

#### dtype
- 배열 요소의 데이터 타입
- ndarray는 한 배열 안에 하나의 dtype을 가짐

| 범주 | 종류 | 요약                      |
|:---|:---|:------------------------|
| 정수형 | `int8`, `int16`, `int32`, `int64` | 부호 있는 정수 타입             |
| 정수형(부호 없음) | `uint8`, `uint16`, `uint32`, `uint64` | 음수 없는 정수 타입             |
| 부동소수형 | `float16`, `float32`, `float64` | 실수 표현 타입                |
| 복소수형 | `complex64`, `complex128` | 실수부와 허수부를 가지는 타입        |
| 불리언형 | `bool_` | `True` 또는 `False` 표현 타입 |
| 문자열형 | `string_`, `bytes_` | 고정 길이 문자열 타입            |
| 유니코드형 | `unicode_` | 다국어 문자 표현 타입            |
| 객체형 | `object_` | Python 객체 참조 저장 타입      |
| 날짜/시간형 | `datetime64`, `timedelta64` | 날짜/시간 저장 타입             |


In [13]:
# 1차원
arr = np.array([1, 2, 3])
print(f'arr : {arr}')
print(f'arr.shape : {arr.shape}') # (3,) -> 1차원에 요소가 3개
print(f'arr.ndim : {arr.ndim}') # 1 -> 1차원 배열
print(f'arr.size : {arr.size}') # 3 -> 저장된 전체 요소 개수 3개
print(f'arr.dtype : {arr.dtype}') # int64 -> 저장된 요소의 타입 int64

arr : [1 2 3]
arr.shape : (3,)
arr.ndim : 1
arr.size : 3
arr.dtype : int64


In [15]:
# 2차원
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(f'arr2 : \n {arr2}') # \n == 줄바꿈
print(f'arr2.shape : {arr2.shape}') # (2, 3)
# 1차원에는 요소 2개(2개의 리스트), 2차원에는 요소가 3개씩 존재(값 3개) == 2행 3열

print(f'arr2.ndim : {arr2.ndim}') # 2(차원)
print(f'arr2.size : {arr2.size}') # 전체 요소 6개
print(f'arr2.dtype : {arr2.dtype}')

arr2 : 
 [[1 2 3]
 [4 5 6]]
arr2.shape : (2, 3)
arr2.ndim : 2
arr2.size : 6
arr2.dtype : int64


In [19]:
# 3차원
temp = [
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
]

arr3 = np.array(temp)
print(f'arr3 : \n {arr3}')
print(f'arr3.shape : {arr3.shape}') # (2, 2, 3)
print(f'arr3.ndim : {arr3.ndim}') # 3
print(f'arr3.size : {arr3.size}') # 12
print(f'arr3.dtype : {arr3.dtype}') # int64

arr3 : 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
arr3.shape : (2, 2, 3)
arr3.ndim : 3
arr3.size : 12
arr3.dtype : int64


### 특정 형식의 ndarray 생성
- `np.zeros(shape)`: 0으로 채워진 ndarray 생성함
- `np.ones(shape)`: 1로 채워진 ndarray 생성함
- `np.full(shape, n)`: 특정 값으로 채워진 ndarray 생성함
- `np.zeros_like(ndarray)`: 기존 배열과 같은 shape의 0 배열 생성함
- `np.ones_like(ndarray)`: 기존 배열과 같은 shape의 1 배열 생성함
- `np.full_like(ndarray, n)`: 기존 배열과 같은 shape의 특정 값 배열 생성함


In [21]:
# np.zeros(shape:tuple, [dtype=float]) : 0으로 채우기
arr1 = np.zeros((3, 2))
print(f'arr1 : \n {arr1}')

arr2 = np.zeros((2, 4), dtype=int)
print(f'arr2 : \n {arr2}')

arr1 : 
 [[0. 0.]
 [0. 0.]
 [0. 0.]]
arr2 : 
 [[0 0 0 0]
 [0 0 0 0]]


In [26]:
# np.ones(shape:tuple, [dtype=float]) : 1로 채우기
arr3 = np.ones((2, 3, 4))
print(f'arr3 : \n {arr3}')

# np.full(shape:tuple, n) : n으로 채우기
arr4 = np.full((4, 3, 2), 3.3)
print(f'arr4 : \n {arr4}')

arr3 : 
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
arr4 : 
 [[[3.3 3.3]
  [3.3 3.3]
  [3.3 3.3]]

 [[3.3 3.3]
  [3.3 3.3]
  [3.3 3.3]]

 [[3.3 3.3]
  [3.3 3.3]
  [3.3 3.3]]

 [[3.3 3.3]
  [3.3 3.3]
  [3.3 3.3]]]


In [27]:
arr5 = np.array([[10, 20, 30], [40, 50, 60]]) # (2, 3)

# np.zeros_like(ndarray)
print(np.zeros_like(arr5))

# np.ones_like(ndarray)
print(np.ones_like(arr5))

# np.full_like(ndarray, n)
print(np.full_like(arr5, 7))

[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
[[7 7 7]
 [7 7 7]]


### 특정 범위의 ndarray 생성
- `np.arange(start, stop, step)`: `start`부터 `stop` 전까지 `step` 간격으로 생성함
- `np.linspace(start, stop, num)`: `start`부터 `stop`까지 `num`개 균등 간격으로 생성함
- `np.logspace(start, stop, num, base)`: 지수 간격 값을 생성함


In [31]:
# np.arange()는 파이썬의 range()처럼 일정 간격의 숫자 배열 생성
arr1 = np.arange(0, 10)
print(f'arr1 : \n {arr1}') # 0, 1, 2, ... , 8, 9

arr2 = np.arange(0, 10, 2)
print(f'arr2 : \n {arr2}') # 0, 2, 4, 6, 8

arr1 : 
 [0 1 2 3 4 5 6 7 8 9]
arr2 : 
 [0 2 4 6 8]


In [37]:
# np.linspace(start, stop, num) : start부터 stop까지 num개로 쪼개기
# stop까지이므로 stop의 숫자도 포함
arr3 = np.linspace(0, 10, 10)
print(f'arr3 : \n {arr3}')

arr4 = np.linspace(0, 10, 11)
print(f'arr4 : \n {arr4}')

arr3 : 
 [ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
arr4 : 
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [40]:
# np.logspace(start, stop, num, base)
# - start부터 stop까지 num개의 숫자를 지수로 하는 base 거듭제곱
arr5 = np.logspace(1, 10, 10, base=2)
print(f'arr5 : \n {arr5}')

arr6 = np.logspace(1, 10, 10) # base=10 기본값
print(f'arr6 : \n {arr6}')

arr5 : 
 [   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]
arr6 : 
 [1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09 1.e+10]


In [43]:
# ndarray는 하나의 타입(dtype)으로만 요소를 가질 수 있다

# 숫자와 문자열이 혼용되면 NumPy가 자동으로 전체 원소를 저장할 수 있는
# 공통 타입으로 형변환을 시킨다
arr = np.array([1, 2, 3, '4'])
print(f'arr : \n {arr}')
print(f'arr.dtype : {arr.dtype}') # <U21 유니코드

arr : 
 ['1' '2' '3' '4']
arr.dtype : <U21


# ndarray 기초 실습 문제
1. 크기가 4x3인 모든 값이 0인 배열
2. 크기가 3x3인 모든 값이 1인 배열
3. 0에서 20까지 5씩 증가하는 값으로 구성된 배열
4. 0과 1 사이의 4개의 등간격 값을 가진 배열

In [50]:
arr1 = np.zeros((4, 3), dtype=int)
arr2 = np.ones((3, 3), dtype=int)
arr3 = np.arange(0, 20, 5)
arr4 = np.linspace(0, 1, 4)

print(f'arr1 : \n {arr1}')
print(f'arr2 : \n {arr2}')
print(f'arr3 : \n {arr3}')
print(f'arr4 : \n {arr4}')

arr1 : 
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
arr2 : 
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
arr3 : 
 [ 0  5 10 15 20]
arr4 : 
 [0.         0.33333333 0.66666667 1.        ]
