# ndarray 연산
- NumPy 배열 간 연산 정리임
- 원소별 연산, broadcasting, 행렬곱, axis 연산 포함함


In [1]:
import numpy as np

## n차원 배열 연산
- 같은 shape끼리 원소별 연산 가능함
- 같은 위치의 값끼리 계산함
- 결과 shape도 기존 shape와 같음


In [13]:
arr1 = np.arange(1, 10).reshape(3, 3)
arr2 = np.full_like(arr1, 2)

# print(f'arr1 + arr2 : \n {arr1 + arr2}')
# print(f'arr1 - arr2 : \n {arr1 - arr2}')
# print(f'arr1 * arr2 : \n {arr1 * arr2}')
# print(f'arr1 / arr2 : \n {arr1 / arr2}')
# print(f'arr1 // arr2 : \n {arr1 // arr2}')
# print(f'arr1 % arr2 : \n {arr1 % arr2}')
print(f'arr1 ** arr2 : \n {arr1 ** arr2}')

arr1 ** arr2 : 
 [[ 1  4  9]
 [16 25 36]
 [49 64 81]]


## broadcasting 연산 방식
- shape가 다른 배열도 규칙이 맞으면 연산 가능함
- 작은 배열을 큰 배열 shape에 맞춰 해석함
- 실제 배열을 복사해서 키우는 것은 아님

**broadcasting 규칙**
- 뒤쪽 차원부터 비교함
- 두 차원이 같으면 가능함
- 둘 중 하나가 1이면 가능함
- 둘 다 다르고 1도 아니면 불가함

![](https://d.pr/i/D0XITM+)
![](https://d.pr/i/fka9ED+)


In [19]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
# arr1 = np.arange(1, 7).reshape(2, 3)
arr2 = np.full((3, ), 2) # [2, 2, 2]

print(f'arr1 : \n {arr1}')
print(f'arr2 : \n {arr2}')

print(f'arr1 + arr2 : \n {arr1 + arr2}')

arr1 : 
 [[1 2 3]
 [4 5 6]]
arr2 : 
 [2 2 2]
arr1 + arr2 : 
 [[3 4 5]
 [6 7 8]]


In [21]:
arr = np.array([1, 2])
print(arr.shape) # (2, )

print(arr1 + arr)
# (2, 3) + (1, 2)
# - 제일 끝 차원인 3, 2가 같지 않고, 둘 중 1이 없음
# -> broadcasting 불가

(2,)


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [25]:
# 스칼라(값 1개) 또는 길이(size)가 1인 배열과의 연산
# -> 전체 원소에 스칼라 또는 배열의 값을 적용

print(f'arr1 : \n {arr1}')
print(f'arr1 + 10 : \n {arr1 + 10}')
print(f'arr1 + [10] : \n {arr1 + [10]}')
print(f'arr1 + [[10]] : \n {arr1 + [[10]]}')
print(f'arr1 + [[[10]]] : \n {arr1 + [[[10]]]}')

arr1 : 
 [[1 2 3]
 [4 5 6]]
arr1 + 10 : 
 [[11 12 13]
 [14 15 16]]
arr1 + [10] : 
 [[11 12 13]
 [14 15 16]]
arr1 + [[10]] : 
 [[11 12 13]
 [14 15 16]]
arr1 + [[[10]]] : 
 [[[11 12 13]
  [14 15 16]]]


In [28]:
arr3 = np.array([[1], [2]])
print(f'arr3 : \n {arr3}') # arr3.shape = (2, 1)
print(f'arr1 : \n {arr1}') # arr1.shape = (2, 3)

print(f'arr1 + arr3 : \n {arr1 + arr3}')
# arr3.shape = (2, 1) -> (2, 3)으로 브로드캐스팅
# [[1, 1, 1]
#  [2, 2, 2]]

arr3 : 
 [[1]
 [2]]
arr1 : 
 [[1 2 3]
 [4 5 6]]
arr1 + arr3 : 
 [[2 3 4]
 [6 7 8]]


In [29]:
arr1 = np.array([[0, 0, 0], [1, 1, 1], [2, 2, 2]])
arr2 = np.array([5, 6, 7])
arr3 = arr1 + arr2

# [[5, 6, 7], [6, 7, 8], [7, 8, 9]]
print(f'arr3 : \n {arr3}')

arr3 : 
 [[5 6 7]
 [6 7 8]
 [7 8 9]]


In [30]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5], [6]])
arr3 = arr1 + arr2

# [[6, 7], [9, 10]]
print(f'arr3 : \n {arr3}')

arr3 : 
 [[ 6  7]
 [ 9 10]]


## 행렬곱셈 Matrix Multiplication
- 점곱연산 Dot Product, 내적이라고도 함
- NumPy의 `*` 연산과 행렬곱은 다름
- `*`: 같은 위치 원소끼리 곱함
- `@`, `np.dot()`, `np.matmul()`: 행렬곱 수행함

**계산 방식**
- 왼쪽 행과 오른쪽 열을 짝지어 계산함
- 같은 위치끼리 곱한 뒤 모두 더함
- 결과의 한 칸은 왼쪽 행과 오른쪽 열의 내적값임

**shape 조건**
- 첫 번째 행렬의 열 수와 두 번째 행렬의 행 수가 같아야 함
- 행렬곱 shape: `(m, n) @ (n, p) -> (m, p)`
- 결과 shape: 바깥쪽 숫자인 `(m, p)`


- **수식**: 행렬 $ A $가 $ m \times n $ 크기이고, 행렬 $ B $가 $ n \times p $ 크기일 때, 행렬 곱 $ A \times B $의 결과는 $ m \times p $ 크기의 행렬이다. 곱셈 과정은 다음과 같다:
  $$
  (A \times B)_{ij} = \sum_{k=1}^{n} A_{ik} \times B_{kj}
  $$
  즉, $ A $의 i번째 행과 $ B $의 j번째 열에 해당하는 원소들을 곱하고, 그 결과를 더하여 새로운 행렬의 $ (i, j) $ 위치에 배치한다.

- **예시**:
  $$
  A = \begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix}, \quad B = \begin{pmatrix} 5 & 6 \\ 7 & 8 \end{pmatrix}
  $$
  $$
  A \times B = \begin{pmatrix} 1 \cdot 5 + 2 \cdot 7 & 1 \cdot 6 + 2 \cdot 8 \\ 3 \cdot 5 + 4 \cdot 7 & 3 \cdot 6 + 4 \cdot 8 \end{pmatrix} = \begin{pmatrix} 19 & 22 \\ 43 & 50 \end{pmatrix}
  $$

- **결과**: 새로운 **행렬**.

In [34]:
a = [[1, 2],
     [3, 4]]
b = [[5, 6],
     [7, 8]]

a = np.array(a)
b = np.array(b)

# NumPy * 연산
print(f'a * b : \n {a * b}')

# 내적 연산(행렬 곱)
# print(f'np.matmul(a, b) : \n {np.matmul(a, b)}')
# print(f'np.dot(a, b) : \n {np.dot(a, b)}')
print(f'a @ b : \n {a @ b}')

a * b : 
 [[ 5 12]
 [21 32]]
a @ b : 
 [[19 22]
 [43 50]]


In [35]:
c = np.array([[1, 2]])   # [1 2] [1 2]
d = np.array([[3], [4]]) # [3 3] [4 4]

print(f'c @ d : \n {c @ d}')

c @ d : 
 [[11]]


In [45]:

f = np.array([[7, 8],
              [9, 10],
              [11, 12]])

e = np.array([[1, 2, 3],
              [4, 5, 6]])

# print(f'e @ f : \n {e @ f}')

# print(f'f @ e : \n {f @ e}')

print('e @ f :')
print(e@f)
print()
print('f @ e :')
print(f@e)

e @ f :
[[ 58  64]
 [139 154]]

f @ e :
[[ 39  54  69]
 [ 49  68  87]
 [ 59  82 105]]


## 기타 연산
- 절대값, 반올림, 올림, 내림, 버림 등 기본 수학 함수 정리임


In [ ]:
# 절대값
arr1 = np.array([[1, -2], [3, -4]])
print(np.abs(arr1))

In [40]:
# ceil, floor, round, trunc
# 올림,  내림,  반올림, 버림
arr2 = np.array([-1.234, 1.234, 2.345, 3.456, 4.567])
print(f'np.ceil(arr2) : \n {np.ceil(arr2)}')
print(f'np.floor(arr2) : \n {np.floor(arr2)}')

print(f'np.round(arr2) : \n {np.round(arr2)}')
print(f'np.trunc(arr2) : \n {np.trunc(arr2)}')

### axis 속성
- 연산을 처리할 축 지정값임
- `axis=None`: 전체 값을 하나로 펼쳐 계산함
- `axis=0`: 행 방향으로 내려가며 계산함, 열별 결과가 남음
- `axis=1`: 열 방향으로 이동하며 계산함, 행별 결과가 남음
- 핵심: axis는 계산 후 사라지는 축임


In [46]:
arr = np.arange(1, 7).reshape(2, 3)

# 최솟값 구하기
print(f'arr.min(axis=None) : \n {arr.min(axis=None)}') # 전체 최솟값

# axis=0 : 행 방향으로 내려가면서 같은 열의 최솟값 구하기
print(f'arr.min(axis=0) : \n {arr.min(axis=0)}')

# axis=1 : 열 방향으로 내려가면서 같은 행의 최솟값 구하기
print(f'arr.min(axis=1) : \n {arr.min(axis=1)}')

arr.min(axis=None) : 
 1
arr.min(axis=0) : 
 [1 2 3]
arr.min(axis=1) : 
 [1 4]


In [48]:
# 합계
print(f'arr.sum() : \n {arr.sum()}') # axis 미작성 == 기본값 ( axis=None )
print(f'arr.sum(axis=0) : \n {arr.sum(axis=0)}')
print(f'arr.sum(axis=1) : \n {arr.sum(axis=1)}')

arr.sum() : 
 21
arr.sum(axis=0) : 
 [5 7 9]
arr.sum(axis=1) : 
 [ 6 15]


In [49]:
# 평균 ndarray.mean() (mean == 수학적으로 평균이라는 뜻)
print(f'arr.mean() : \n {arr.mean()}')
print(f'arr.mean(axis=0) : \n {arr.mean(axis=0)}')
print(f'arr.mean(axis=1) : \n {arr.mean(axis=1)}')

arr.mean() : 
 3.5
arr.mean(axis=0) : 
 [2.5 3.5 4.5]
arr.mean(axis=1) : 
 [2. 5.]
